### ISSUE TITLE
Errors on macOS Big Sur?

### ISSUE THREAD

**Issue by chrisspiegl** [bradmontgomery/alfred-percent-change#4]
Not sure why this issue started showing up but I am getting this error when I try to run this workflow:

```
Code 1: Traceback (most recent call last):
  File "/Users/spieglio/Documents/Alfred-Course-Preferences/Alfred.alfredpreferences/workflows/user.workflow.CF498365-FC95-454E-9B6A-8ED1AD20F5EB/percent.py", line 27, in <module>
    from workflow import Workflow, ICON_INFO
  File "/Users/spieglio/Documents/Alfred-Course-Preferences/Alfred.alfredpreferences/workflows/user.workflow.CF498365-FC95-454E-9B6A-8ED1AD20F5EB/workflow/__init__.py", line 16, in <module>
    from .workflow import Workflow, manager
  File "/Users/spieglio/Documents/Alfred-Course-Preferences/Alfred.alfredpreferences/workflows/user.workflow.CF498365-FC95-454E-9B6A-8ED1AD20F5EB/workflow/workflow.py", line 27, in <module>
    import cPickle
ModuleNotFoundError: No module named 'cPickle'
```

Maybe this could be fixed?

**Comment by bradmontgomery** [comment]
Hi @chrisspiegl thanks for the report.  This looks like Big Sur may have defaulted to python3.  I'll give it a test drive as soon as I can & post an update.

**Comment by bradmontgomery** [comment]
@chrisspiegl Try the latest release and let me know if you have any issues. https://github.com/bradmontgomery/alfred-percent-change/blob/v1.6.0/PercentChange1-6.alfredworkflow

**Comment by chrisspiegl** [comment]
@bradmontgomery I installed this and it worked. 👍
Thanks for the update.

Tested on macOS 12.3 on M1 Max
